---
name: Tie-Array-BoundedIndex
version: 0.03
author:
  - Peter Scott, C<pjs-cpan@PSDT.com>.
abstract: Bounded arrays
license: perl
provides:
  Tie::Array::BoundedIndex:
    file: lib/Tie/Array/BoundedIndex.pm
    version: 0.03
generated_by: Module::Build version 0.261
