--- #YAML:1.0
name: Tie-Array-BoundedIndex
version: 0.02
license: perl
distribution_type: module
requires: {}
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Tie::Array::BoundedIndex:
    file: lib/Tie/Array/BoundedIndex.pm
    version: 0.02
generated_by: Module::Build version 0.21
